### PR TITLE
Notebook execution and text in testing section

### PR DESCRIPTION
**Pull request by womullan**

### CODE REVIEW

**Comment by adambolton** [comment]
Looks good, my only question is why are the First/Last IDs different between Summit and USDF in 3.1.1?

**Comment by jchiang87** [comment]
The `registry.queryDatasets `call doesn't always return the dataset refs in the same order since I believe the outputs are aggregated from several db queries.  In retrospect, we probably should have sorted those so they would match.

**Review by adambolton — COMMENTED** [review]
Reviewed rendered doc, looks good. Question about first/last answered in comment thread. OK for merge to main.

**Comment by jchiang87** [comment]
Thanks, I'll tag 1.0 and merge.

**Pull request merged**
